### ISSUE TITLE
Bullets look weird

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-admintool#39]
<img width="390" alt="image" src="https://github.com/iftechfoundation/ifarchive-admintool/assets/96150/3407af5e-3845-4c7a-a21e-e326585c1ed4">

https://upload.ifarchive.org/misc/admintool.css

```css
ul {
    list-style: url("cssbullet.png");
    margin-left: 10px;
    padding-left: 9px;
    border-left: 3px solid #F0D0A0;
}
```

Bullets _and_ a border seems wrong to me. I feel like it should be one or the other.

**Comment by erkyrath** [comment]
Sigh. They're supposed to look like this:

<img width="274" alt="Untitled" src="https://github.com/iftechfoundation/ifarchive-admintool/assets/65666/a0add0be-912c-4550-a2b8-f428a02b310c">

My pixel-perfect alignment is Safari-only, I guess.

Nonetheless, I want both the grouping effect of the border and the start indication provided by the bullets. Omitting either was poor design -- I tried it.

**Comment by dfabulich** [comment]
Those bullets aren't pixel-perfect on Safari, either. When you zoom in on your scerenshot, you'll see that the bullet is slightly off-center.

<img alt="Untitled" width="900" src="https://private-user-images.githubusercontent.com/65666/294219679-a0add0be-912c-4550-a2b8-f428a02b310c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjEzMTAsIm5iZiI6MTcwNDQyMTAxMCwicGF0aCI6Ii82NTY2Ni8yOTQyMTk2NzktYTBhZGQwYmUtOTEyYy00NTUwLWEyYjgtZjQyOGEwMmIzMTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAyMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNGYzNGE5NGRkNTAzNmQ3ZDMwNjAyZWQ3ZGE5NWUxYjgxYTNmZGQwNjExNzVlZDc3ODlmOGFkZmI2NzAyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSkRaInl3SaYfnrOd66Bzfup0rUtJSvKT4VmRJgsoO8">
> My pixel-perfect alignment is Safari-only, I guess.

If we want both a border and bullets, why not separate them, like this?

```css
ul {
    list-style: url("cssbullet.png");
    margin-left: 10px;
    padding-left: 18px;
    border-left: 3px solid #F0D0A0;
}
```

<img width="348" alt="image" src="https://github.com/iftechfoundation/ifarchive-admintool/assets/96150/1f5915ee-5728-4eb0-a71b-b2d0faf30924">
